name: Build and Release Windows Executable
on:
  workflow_dispatch:
  release:
    types: [ created ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build and Compress Executable
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Build Executable with Make
        run: make build

      - name: Upload Executable to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/BafinDownloader.exe
          tag: ${{ github.ref }}