name: Build and Release Windows Executable
on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  release-windows:
    name: Build Windows Executable
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: windows
        goarch: amd64
        ldflags: -s -w
