name: Build and Release Windows Executable
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'set release tag'
        required: true
        type: boolean
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  release-windows:
    name: Build Windows Executable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: windows
        goarch: amd64
        build_command: make
        executable_compression: upx
        binary_name: BafinDownloader
        asset_name: BafinDownloader
        md5sum: false
