name: Build and Release Windows Executable
on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  build:
    name: Build and Compress Executable
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Install UPX
        run: choco install upx

      - name: Build Executable with Make
        run: make build

      - name: Compress Executable with UPX
        run: upx /bin/BafinDownloader.exe

      - name: Upload Executable to Release
        uses: softprops/action-gh-release@v1
        with:
          files: /bin/BafinDownloader.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}